name: commands

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - README.md
      - .github/workflows/check-commands.yml
  push:
    branches:
      - main
    paths:
      - README.md
      - .github/workflows/check-commands.yml

jobs:
  command-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check commands in README.md file
        run: sed -n "/^\`\`\`bash.*/,/^\`\`\`$/p" README.md | sed "/^\`\`\`*/d" | bash -x
