---
# GitHub Actions workflow for Markdown linting and link checking
# Validates Markdown files and checks for broken links when content is modified
# https://github.com/DavidAnson/markdownlint
name: markdown-check

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main
    paths:
      - "**.md"
      - .github/workflows/markdown-check.yml
      - .markdownlint.yml

permissions: read-all

jobs:
  markdownlint-check:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - name: Markdown Lint
        uses: ruzickap/action-my-markdown-linter@5e4b49fb65d856a021b96ad7f799cc3bde9af91e # v1.3.0
        with:
          exclude: |
            tests/
            CHANGELOG.md

  markdown-link-check:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - name: Link Checker
        uses: ruzickap/action-my-markdown-link-checker@0bc23ed1091ca59159fb6e2bd05112a942fb7f70 # v1.5.0
        with:
          exclude: |
            tests/
            CHANGELOG.md
